config/routes.rb
Rails.application.routes.draw do

  resources :man_boards
  get 'said_zekrs/user' => 'said_zekrs#index', as: 'user_said_zekrs'
  get 'readed_namazs/user' => 'readed_namazs#index', as: 'user_readed_namazs'

  resources :said_zekrs do
    member do
      get :show_user_said_zekrs
    end
  end

  resources :readed_namazs do
    member do
      get :show_user_namaz
    end
  end

	get 'yadavarezekrs/zekr_id' => 'yadavarezekrs#index', as: 'zekr_yadavarezekrs'
  resources :yadavarezekrs
	get 'yadavarenamazs/namaz_id' => 'yadavarenamazs#index', as: 'namaz_yadavarenamazs'
  resources :yadavarenamazs
	get 'yadavars/user_id' => 'yadavars#index', as: 'user_yadavars'
  resources :yadavars
	get 'zekrs/user_id' => 'zekrs#index', as: 'user_zekrs'
  resources :zekrs
	get 'ruzes/user_id' => 'ruzes#index', as: 'user_ruzes'
  resources :ruzes
	get 'namazs/user_id' => 'namazs#index', as: 'user_namazs'
  resources :namazs

  get 'home/index'

  resources :profiles

  resources :mohrs do
    member do
      get :mohr_input
    end
  end

  devise_for :users

  devise_for :readed_namazs

  root to: "home#index"

end

app/models/man_board.rb
class ManBoard < ActiveRecord::Base
end

app/models/mohr.rb
class Mohr < ActiveRecord::Base
	belongs_to :profile
end

app/models/namaz.rb
class Namaz < ActiveRecord::Base
	belongs_to :user
	has_many :yadavarenamaz
	validates_presence_of :name
	#validates_numericality_of :tedad_rokat, greater_than: :-1
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	has_one :mohr
	validates_presence_of :name
	validates_presence_of :lastname
	validates_presence_of :email
	validates_presence_of :name
	#validates :email,
		#	uniqueness: true
		#		message: "این ایمیل قبلا ثبت شده است، لطفا ایمیل دیگری وارد کنید."
		#	format: {with => Devise::email_regexp}#/\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/}
		#		message: "آدرس ایمیل معتبر نیست. لطفا ایمیل معتبر وارد کنید."

end

app/models/readed_namaz.rb
class ReadedNamaz < ActiveRecord::Base
	 belongs_to :user , class_name: "User"
end

app/models/ruze.rb
class Ruze < ActiveRecord::Base
	belongs_to :user
	has_many :yadavareruze
	validates_presence_of :name
end

app/models/said_zekr.rb
class SaidZekr < ActiveRecord::Base
	belongs_to :user , class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
	 has_one :profile
	 has_many :zekr
	 has_many :yadavar
	 has_many :ruze
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/yadavar.rb
class Yadavar < ActiveRecord::Base
	#belongs_to :namaz
	#belongs_to :zekr
	belongs_to :user
	validates_presence_of :saat
	validates_presence_of :min
end

app/models/yadavarenamaz.rb
class Yadavarenamaz < ActiveRecord::Base
	belongs_to :namaz
	belongs_to :user
	validates_presence_of :saat
	validates_presence_of :min
end

app/models/yadavarezekr.rb
class Yadavarezekr < ActiveRecord::Base
	belongs_to :zekr
	belongs_to :user
	validates_presence_of :saat
	validates_presence_of :min
end

app/models/zekr.rb
class Zekr < ActiveRecord::Base
	belongs_to :user
	has_many :yadavar
	validates_presence_of :name
end

app/controllers/yadavars_controller.rb
class YadavarsController < ApplicationController
  before_action :set_yadavar, only: [:show, :edit, :update, :destroy]

  # GET /yadavars
  # GET /yadavars.json
  def index
    @yadavars = Yadavar.all
  end

  # GET /yadavars/1
  # GET /yadavars/1.json
  def show
  end

  # GET /yadavars/new
  def new
    @yadavar = Yadavar.new
  end

  # GET /yadavars/1/edit
  def edit
  end

  # POST /yadavars
  # POST /yadavars.json
  def create
    @yadavar = Yadavar.new(yadavar_params)
    @yadavar.user_id=current_user.id

    respond_to do |format|
      if @yadavar.save
        format.html { redirect_to @yadavar, notice: 'Yadavar was successfully created.' }
        format.json { render :show, status: :created, location: @yadavar }
      else
        format.html { render :new }
        format.json { render json: @yadavar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yadavars/1
  # PATCH/PUT /yadavars/1.json
  def update
    respond_to do |format|
      if @yadavar.update(yadavar_params)
        format.html { redirect_to @yadavar, notice: 'Yadavar was successfully updated.' }
        format.json { render :show, status: :ok, location: @yadavar }
      else
        format.html { render :edit }
        format.json { render json: @yadavar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yadavars/1
  # DELETE /yadavars/1.json
  def destroy
    @yadavar.destroy
    respond_to do |format|
      format.html { redirect_to yadavars_url, notice: 'Yadavar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_yadavar
      @yadavar = Yadavar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def yadavar_params
      params.require(:yadavar).permit(:saat, :min, :tozihat)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/man_boards_helper.rb
module ManBoardsHelper
end

app/helpers/mohrs_helper.rb
module MohrsHelper
end

app/helpers/namazs_helper.rb
module NamazsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/ruzes_helper.rb
module RuzesHelper
end

app/helpers/said_zekrs_helper.rb
module SaidZekrsHelper
end

app/helpers/yadavars_helper.rb
module YadavarsHelper
end

app/helpers/zekrs_helper.rb
module ZekrsHelper
end

app/views/yadavars/_form.html.erb
<%= form_for(@yadavar) do |f| %>
  <% if @yadavar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@yadavar.errors.count, "error") %> prohibited this yadavar from being saved:</h2>

      <ul>
      <% @yadavar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :saat %><br>
    <%= f.number_field :saat %>
  </div>
  <div class="field">
    <%= f.label :min %><br>
    <%= f.number_field :min %>
  </div>
  <div class="field">
    <%= f.label :tozihat %><br>
    <%= f.text_area :tozihat %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/yadavars/edit.html.erb
<h1>Editing Yadavar</h1>

<%= render 'form' %>

<%= link_to 'Show', @yadavar %> |
<%= link_to 'Back', yadavars_path %>

app/views/yadavars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Yadavars</h1>

<table>
  <thead>
    <tr>
      <th>Saat</th>
      <th>Min</th>
      <th>Tozihat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @yadavars.each do |yadavar| %>
	<% if yadavar.user_id == current_user.id%>
      <tr>
        <td><%= yadavar.saat %></td>
        <td><%= yadavar.min %></td>
        <td><%= yadavar.tozihat %></td>
        <td><%= link_to 'Show', yadavar %></td>
        <td><%= link_to 'Edit', edit_yadavar_path(yadavar) %></td>
        <td><%= link_to 'Destroy', yadavar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
	<% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Yadavar', new_yadavar_path %>

app/views/yadavars/new.html.erb
<h1>New Yadavar</h1>

<%= render 'form' %>

<%= link_to 'Back', yadavars_path %>

app/views/yadavars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Saat:</strong>
  <%= @yadavar.saat %>
</p>

<p>
  <strong>Min:</strong>
  <%= @yadavar.min %>
</p>

<p>
  <strong>Tozihat:</strong>
  <%= @yadavar.tozihat %>
</p>

<%= link_to 'Edit', edit_yadavar_path(@yadavar) %> |
<%= link_to 'Back', yadavars_path %>