config/routes.rb
Rails.application.routes.draw do

  resources :man_boards
  get 'said_zekrs/user' => 'said_zekrs#index', as: 'user_said_zekrs'
  get 'readed_namazs/user' => 'readed_namazs#index', as: 'user_readed_namazs'

  resources :said_zekrs do
    member do
      get :show_user_said_zekrs
    end
  end

  resources :readed_namazs do
    member do
      get :show_user_namaz
    end
  end

	get 'yadavarezekrs/zekr_id' => 'yadavarezekrs#index', as: 'zekr_yadavarezekrs'
  resources :yadavarezekrs
	get 'yadavarenamazs/namaz_id' => 'yadavarenamazs#index', as: 'namaz_yadavarenamazs'
  resources :yadavarenamazs
	get 'yadavars/user_id' => 'yadavars#index', as: 'user_yadavars'
  resources :yadavars
	get 'zekrs/user_id' => 'zekrs#index', as: 'user_zekrs'
  resources :zekrs
	get 'ruzes/user_id' => 'ruzes#index', as: 'user_ruzes'
  resources :ruzes
	get 'namazs/user_id' => 'namazs#index', as: 'user_namazs'
  resources :namazs

  get 'home/index'

  resources :profiles

  resources :mohrs do
    member do
      get :mohr_input
    end
  end

  devise_for :users

  devise_for :readed_namazs

  root to: "home#index"

end

app/models/man_board.rb
class ManBoard < ActiveRecord::Base
end

app/models/mohr.rb
class Mohr < ActiveRecord::Base
	belongs_to :profile
end

app/models/namaz.rb
class Namaz < ActiveRecord::Base
	belongs_to :user
	has_many :yadavarenamaz
	validates_presence_of :name
	#validates_numericality_of :tedad_rokat, greater_than: :-1
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	has_one :mohr
	validates_presence_of :name
	validates_presence_of :lastname
	validates_presence_of :email
	validates_presence_of :name
	#validates :email,
		#	uniqueness: true
		#		message: "این ایمیل قبلا ثبت شده است، لطفا ایمیل دیگری وارد کنید."
		#	format: {with => Devise::email_regexp}#/\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/}
		#		message: "آدرس ایمیل معتبر نیست. لطفا ایمیل معتبر وارد کنید."

end

app/models/readed_namaz.rb
class ReadedNamaz < ActiveRecord::Base
	 belongs_to :user , class_name: "User"
end

app/models/ruze.rb
class Ruze < ActiveRecord::Base
	belongs_to :user
	has_many :yadavareruze
	validates_presence_of :name
end

app/models/said_zekr.rb
class SaidZekr < ActiveRecord::Base
	belongs_to :user , class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
	 has_one :profile
	 has_many :zekr
	 has_many :yadavar
	 has_many :ruze
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/yadavar.rb
class Yadavar < ActiveRecord::Base
	#belongs_to :namaz
	#belongs_to :zekr
	belongs_to :user
	validates_presence_of :saat
	validates_presence_of :min
end

app/models/yadavarenamaz.rb
class Yadavarenamaz < ActiveRecord::Base
	belongs_to :namaz
	belongs_to :user
	validates_presence_of :saat
	validates_presence_of :min
end

app/models/yadavarezekr.rb
class Yadavarezekr < ActiveRecord::Base
	belongs_to :zekr
	belongs_to :user
	validates_presence_of :saat
	validates_presence_of :min
end

app/models/zekr.rb
class Zekr < ActiveRecord::Base
	belongs_to :user
	has_many :yadavar
	validates_presence_of :name
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
		@time = Time.now
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/man_boards_helper.rb
module ManBoardsHelper
end

app/helpers/mohrs_helper.rb
module MohrsHelper
end

app/helpers/namazs_helper.rb
module NamazsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/ruzes_helper.rb
module RuzesHelper
end

app/helpers/said_zekrs_helper.rb
module SaidZekrsHelper
end

app/helpers/yadavars_helper.rb
module YadavarsHelper
end

app/helpers/zekrs_helper.rb
module ZekrsHelper
end

app/views/home/index.html.erb
<!--<h1>Home#index</h1>
<p>
<!--be name anke parvane heirane ust.. -->

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">

    <title>DASHGUM - Bootstrap Admin Template</title>

    <!-- Bootstrap core CSS -->
    <link href="assets/css/bootstrap.css" rel="stylesheet">
    <!--external css-->
    <link href="assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
        
    <!-- Custom styles for this template -->
    <link href="assets/css/style.css" rel="stylesheet">
    <link href="assets/css/style-responsive.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

<% if user_signed_in? %>

      <div class="row mtbox">
            <div class="col-md-2 col-sm-2 col-md-offset-1 box0">
                    <div class="box1">
                         <p class="centered">
                           <%= link_to user_namazs_path( :id => current_user.id) do %>
                              <%= image_tag "pics/namaz.png", class: "btn btn-info btn-lg" %>
                           <% end %>
                         </p>
                        <h4>گلبرگ نماز</h4>
                    </div>
                    <p>امام رضا (ع ) :</p>
                    <p>(الصلوة ) صلة الله للعبد بالرحمة</p>
                    <p>نمازعطیه و احسانی است از طرف خداوند برای بنده ، که از راه رحمت و عنایت بخشیده است .</p>
                    <p>( بحار الانوار، ج ,84 ص 246 )</p>
                    
            </div>
            <br><br><br><br>
            <br>
            <br>
            <br>
            <div class="col-md-2 col-sm-2 box0">
                    <div class="box1">
                         <p class="centered">
                           <%= link_to user_zekrs_path( :id => current_user.id) do %>
                              <%= image_tag "pics/tasbih.png", class: "btn btn-warning btn-lg" %>
                           <% end %>
                         </p>
                        <h4>گلبرگ تسبیح</h4>
                    </div>
                    <p>امام باقر(ع):</p>
                    <p> ذکر اللسان الحمد و الثناء و ذکر النفس الجهد و العناء و ذکر الروح الخوف و الرجاء و ذکر القلب الصدق و الصفاء و ذکر العقل التعظیم و الحیاء و ذکر المعرفه التسلیم و الرضا و ذکر السر الرؤیه و اللقاء</p>
                    <p>ذكر زبان حمد و ثناء، ذكر نفس سختكوشى و تحمل رنج، ذكر روح بيم و اميد، ذكر دل صدق و صفا، ذكر عقل تعظيم و شرم، ذكر معرفت تسليم و رضا و ذكر باطن مشاهده و لقا است.</p>
                    <p>مشكاة الانوار ص 55-به نقل از http://www.aviny.com/</p>
            </div>
             <br><br><br><br>
            <br>
            <br>
            <br>
            <div class="col-md-2 col-sm-2 box0">
                    <div class="box1">
                         <p class="centered">
                           <%= link_to user_ruzes_path( :id => current_user.id) do %>
                              <%= image_tag "pics/ruze.png", class: "btn btn-success btn-lg" %>
                           <% end %>
                         </p>
                        <h4>گلبرگ روزه</h4>
                    </div>
                    <p>پیامبر (ص):</p>
                    <p>لو یعلم العبد ما فى رمضان لود ان یكون رمضان السنة</p>
                    <p>اگر بنده (خدا) مى‏دانست كه در ماه رمضان چیست [چه بركتى وجود دارد] دوست مى‏داشت كه تمام سال، رمضان باشد. </p>
                    <p>(بحار الانوار، ج 93، ص 346 )</p>
            </div>
                          
       </div><!-- /row mt -->

<% else %>
	          
      <!-- **********************************************************************************************************************************************************
      MAIN CONTENT
      *********************************************************************************************************************************************************** -->

	  <div id="login-page">
	  	<div class="container">
	  		
	  		  
		      <form class="form-login" action="index.html">
		      	<p class="centered"><a href="profile.html"><img src="/assets/login/icon.png" class="img-circle" width="60"></a></p>
			                  <!--<h5 class="centered">سرو مهر</h5>-->
		        <h2 class="form-login-heading">به سرو مهر خوش آمدید.</h2>
		        <div class="login-wrap">
		            
		            <%= link_to "ورود", new_user_session_path , :class=>"btn btn-theme btn-block" %>
		          
		            <hr>
		            
		            <div class="registration">
		                ثبت نام نکرده اید؟<br/>
		                <%= link_to "ثبت نام", new_user_registration_path , :class=>"btn btn-round btn-warning" %>
		            </div>
		
		        </div>
		

		
		      </form>	  	
	  	
	  	</div>
	  </div>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="assets/js/jquery.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>

    <!--BACKSTRETCH-->
    <!-- You can use an image of whatever size. This script will stretch to fit in any screen size.-->
    <script type="text/javascript" src="assets/js/jquery.backstretch.min.js"></script>
    <script>
        $.backstretch("assets/img/login-bg.jpg", {speed: 500});
    </script>




<% end %>

  </body>
</html>