config/routes.rb
Rails.application.routes.draw do

  resources :man_boards
  get 'said_zekrs/user' => 'said_zekrs#index', as: 'user_said_zekrs'
  get 'readed_namazs/user' => 'readed_namazs#index', as: 'user_readed_namazs'

  resources :said_zekrs do
    member do
      get :show_user_said_zekrs
    end
  end

  resources :readed_namazs do
    member do
      get :show_user_namaz
    end
  end

	get 'yadavarezekrs/zekr_id' => 'yadavarezekrs#index', as: 'zekr_yadavarezekrs'
  resources :yadavarezekrs
	get 'yadavarenamazs/namaz_id' => 'yadavarenamazs#index', as: 'namaz_yadavarenamazs'
  resources :yadavarenamazs
	get 'yadavars/user_id' => 'yadavars#index', as: 'user_yadavars'
  resources :yadavars
	get 'zekrs/user_id' => 'zekrs#index', as: 'user_zekrs'
  resources :zekrs
	get 'ruzes/user_id' => 'ruzes#index', as: 'user_ruzes'
  resources :ruzes
	get 'namazs/user_id' => 'namazs#index', as: 'user_namazs'
  resources :namazs

  get 'home/index'

  resources :profiles

  resources :mohrs do
    member do
      get :mohr_input
    end
  end

  devise_for :users

  devise_for :readed_namazs

  root to: "home#index"

end

app/models/man_board.rb
class ManBoard < ActiveRecord::Base
end

app/models/mohr.rb
class Mohr < ActiveRecord::Base
	belongs_to :profile
end

app/models/namaz.rb
class Namaz < ActiveRecord::Base
	belongs_to :user
	has_many :yadavarenamaz
	validates_presence_of :name
	#validates_numericality_of :tedad_rokat, greater_than: :-1
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	has_one :mohr
	validates_presence_of :name
	validates_presence_of :lastname
	validates_presence_of :email
	validates_presence_of :name
	#validates :email,
		#	uniqueness: true
		#		message: "این ایمیل قبلا ثبت شده است، لطفا ایمیل دیگری وارد کنید."
		#	format: {with => Devise::email_regexp}#/\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/}
		#		message: "آدرس ایمیل معتبر نیست. لطفا ایمیل معتبر وارد کنید."

end

app/models/readed_namaz.rb
class ReadedNamaz < ActiveRecord::Base
	 belongs_to :user , class_name: "User"
end

app/models/ruze.rb
class Ruze < ActiveRecord::Base
	belongs_to :user
	has_many :yadavareruze
	validates_presence_of :name
end

app/models/said_zekr.rb
class SaidZekr < ActiveRecord::Base
	belongs_to :user , class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
	 has_one :profile
	 has_many :zekr
	 has_many :yadavar
	 has_many :ruze
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/yadavar.rb
class Yadavar < ActiveRecord::Base
	#belongs_to :namaz
	#belongs_to :zekr
	belongs_to :user
	validates_presence_of :saat
	validates_presence_of :min
end

app/models/yadavarenamaz.rb
class Yadavarenamaz < ActiveRecord::Base
	belongs_to :namaz
	belongs_to :user
	validates_presence_of :saat
	validates_presence_of :min
end

app/models/yadavarezekr.rb
class Yadavarezekr < ActiveRecord::Base
	belongs_to :zekr
	belongs_to :user
	validates_presence_of :saat
	validates_presence_of :min
end

app/models/zekr.rb
class Zekr < ActiveRecord::Base
	belongs_to :user
	has_many :yadavar
	validates_presence_of :name
end

app/controllers/zekrs_controller.rb
class ZekrsController < ApplicationController
  before_action :set_zekr, only: [:show, :edit, :update, :destroy]

  # GET /zekrs
  # GET /zekrs.json
 
	def index
	#if params[:user_id]
	#@user = User.where(user_id: params[:user_id]).first
	#@zekrs = @user.zekrs
	#else
	@zekrs = Zekr.all
	end
	#end


  # GET /zekrs/1
  # GET /zekrs/1.json
  def show
  end

  # GET /zekrs/new
  def new
    @zekr = Zekr.new
  end

  # GET /zekrs/1/edit
  def edit
  end

  # POST /zekrs
  # POST /zekrs.json
  def create
    @zekr = Zekr.new(zekr_params)
    @zekr.user_id=current_user.id
    respond_to do |format|
      if @zekr.save
        format.html { redirect_to @zekr, notice: 'Zekr was successfully created.' }
        format.json { render :show, status: :created, location: @zekr }
      else
        format.html { render :new }
        format.json { render json: @zekr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zekrs/1
  # PATCH/PUT /zekrs/1.json
  def update
    respond_to do |format|
      if @zekr.update(zekr_params)
        format.html { redirect_to @zekr, notice: 'Zekr was successfully updated.' }
        format.json { render :show, status: :ok, location: @zekr }
      else
        format.html { render :edit }
        format.json { render json: @zekr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zekrs/1
  # DELETE /zekrs/1.json
  def destroy
    @zekr.destroy
    respond_to do |format|
      format.html { redirect_to zekrs_url, notice: 'Zekr was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zekr
      @zekr = Zekr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zekr_params
      params.require(:zekr).permit(:name, :tozihat, :tedad)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/man_boards_helper.rb
module ManBoardsHelper
end

app/helpers/mohrs_helper.rb
module MohrsHelper
end

app/helpers/namazs_helper.rb
module NamazsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/ruzes_helper.rb
module RuzesHelper
end

app/helpers/said_zekrs_helper.rb
module SaidZekrsHelper
end

app/helpers/yadavars_helper.rb
module YadavarsHelper
end

app/helpers/zekrs_helper.rb
module ZekrsHelper
end

app/views/zekrs/_form.html.erb
<%= form_for(@zekr) do |f| %>
  <% if @zekr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zekr.errors.count, "error") %> prohibited this zekr from being saved:</h2>

      <ul>
      <% @zekr.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tozihat %><br>
    <%= f.text_area :tozihat %>
  </div>
  <div class="field">
    <%= f.label :tedad %><br>
    <%= f.number_field :tedad %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zekrs/edit.html.erb
<h1>Editing Zekr</h1>

<%= render 'form' %>

<%= link_to 'Show', @zekr %> |
<%= link_to 'Back', zekrs_path %>

app/views/zekrs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Zekrs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tozihat</th>
      <th>Tedad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zekrs.each do |zekr| %>
<!*^*^>
	<% if zekr.user_id == current_user.id%>
      <tr>
        <td><%= zekr.name %></td>
        <td><%= zekr.tozihat %></td>
        <td><%= zekr.tedad %></td>
	

	<td><%= link_to "Yadavarha", yadavarezekrs_path(:zekr_id => zekr.id) %></td>
        <td><%= link_to 'Show', zekr %></td>
        <td><%= link_to 'Edit', edit_zekr_path(zekr) %></td>
        <td><%= link_to 'Destroy', zekr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
	<%end%>
    <% end %>
  </tbody>
</table>

<br>

<!*^*^>
<%= link_to 'New Zekr', new_zekr_path %>

app/views/zekrs/new.html.erb
<h1>New Zekr</h1>

<%= render 'form' %>

<%= link_to 'Back', zekrs_path %>

app/views/zekrs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @zekr.name %>
</p>

<p>
  <strong>Tozihat:</strong>
  <%= @zekr.tozihat %>
</p>

<p>
  <strong>Tedad:</strong>
  <%= @zekr.tedad %>
</p>

<%= link_to 'Edit', edit_zekr_path(@zekr) %> |
<%= link_to 'Back', zekrs_path %>