config/routes.rb
Rails.application.routes.draw do

  resources :man_boards
  get 'said_zekrs/user' => 'said_zekrs#index', as: 'user_said_zekrs'
  get 'readed_namazs/user' => 'readed_namazs#index', as: 'user_readed_namazs'

  resources :said_zekrs do
    member do
      get :show_user_said_zekrs
    end
  end

  resources :readed_namazs do
    member do
      get :show_user_namaz
    end
  end

	get 'yadavarezekrs/zekr_id' => 'yadavarezekrs#index', as: 'zekr_yadavarezekrs'
  resources :yadavarezekrs
	get 'yadavarenamazs/namaz_id' => 'yadavarenamazs#index', as: 'namaz_yadavarenamazs'
  resources :yadavarenamazs
	get 'yadavars/user_id' => 'yadavars#index', as: 'user_yadavars'
  resources :yadavars
	get 'zekrs/user_id' => 'zekrs#index', as: 'user_zekrs'
  resources :zekrs
	get 'ruzes/user_id' => 'ruzes#index', as: 'user_ruzes'
  resources :ruzes
	get 'namazs/user_id' => 'namazs#index', as: 'user_namazs'
  resources :namazs

  get 'home/index'

  resources :profiles

  resources :mohrs do
    member do
      get :mohr_input
    end
  end

  devise_for :users

  devise_for :readed_namazs

  root to: "home#index"

end

app/models/man_board.rb
class ManBoard < ActiveRecord::Base
end

app/models/mohr.rb
class Mohr < ActiveRecord::Base
	belongs_to :profile
end

app/models/namaz.rb
class Namaz < ActiveRecord::Base
	belongs_to :user
	has_many :yadavarenamaz
	validates_presence_of :name
	#validates_numericality_of :tedad_rokat, greater_than: :-1
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	has_one :mohr
	validates_presence_of :name
	validates_presence_of :lastname
	validates_presence_of :email
	validates_presence_of :name
	#validates :email,
		#	uniqueness: true
		#		message: "این ایمیل قبلا ثبت شده است، لطفا ایمیل دیگری وارد کنید."
		#	format: {with => Devise::email_regexp}#/\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/}
		#		message: "آدرس ایمیل معتبر نیست. لطفا ایمیل معتبر وارد کنید."

end

app/models/readed_namaz.rb
class ReadedNamaz < ActiveRecord::Base
	 belongs_to :user , class_name: "User"
end

app/models/ruze.rb
class Ruze < ActiveRecord::Base
	belongs_to :user
	has_many :yadavareruze
	validates_presence_of :name
end

app/models/said_zekr.rb
class SaidZekr < ActiveRecord::Base
	belongs_to :user , class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
	 has_one :profile
	 has_many :zekr
	 has_many :yadavar
	 has_many :ruze
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/yadavar.rb
class Yadavar < ActiveRecord::Base
	#belongs_to :namaz
	#belongs_to :zekr
	belongs_to :user
	validates_presence_of :saat
	validates_presence_of :min
end

app/models/yadavarenamaz.rb
class Yadavarenamaz < ActiveRecord::Base
	belongs_to :namaz
	belongs_to :user
	validates_presence_of :saat
	validates_presence_of :min
end

app/models/yadavarezekr.rb
class Yadavarezekr < ActiveRecord::Base
	belongs_to :zekr
	belongs_to :user
	validates_presence_of :saat
	validates_presence_of :min
end

app/models/zekr.rb
class Zekr < ActiveRecord::Base
	belongs_to :user
	has_many :yadavar
	validates_presence_of :name
end

app/controllers/said_zekrs_controller.rb
class SaidZekrsController < ApplicationController
  before_action :set_said_zekr, only: [:show, :edit, :update, :destroy]

  # GET /said_zekrs
  # GET /said_zekrs.json
  def index
    @user = current_user
    @said_zekrs = SaidZekr.where(user_id: @user)
  end

  # GET /said_zekrs/1
  # GET /said_zekrs/1.json
  def show
  end

  # GET /said_zekrs/new
  def new
    @said_zekr = SaidZekr.new
  end

  # GET /said_zekrs/1/edit
  def edit
  end

  # POST /said_zekrs
  # POST /said_zekrs.json
  def create
    @said_zekr = SaidZekr.new(said_zekr_params)

    respond_to do |format|
      if @said_zekr.save
        format.html { redirect_to @said_zekr, notice: 'Said zekr was successfully created.' }
        format.json { render :show, status: :created, location: @said_zekr }
      else
        format.html { render :new }
        format.json { render json: @said_zekr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /said_zekrs/1
  # PATCH/PUT /said_zekrs/1.json
  def update
    respond_to do |format|
      if @said_zekr.update(said_zekr_params)
        format.html { redirect_to @said_zekr, notice: 'Said zekr was successfully updated.' }
        format.json { render :show, status: :ok, location: @said_zekr }
      else
        format.html { render :edit }
        format.json { render json: @said_zekr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /said_zekrs/1
  # DELETE /said_zekrs/1.json
  def destroy
    @said_zekr.destroy
    respond_to do |format|
      format.html { redirect_to said_zekrs_url, notice: 'Said zekr was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show_user_said_zekrs
    @user = User.find(params[:id])
    @said_zekrs = SaidZekr.where(user_id: @user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_said_zekr
      @said_zekr = SaidZekr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def said_zekr_params
      params.require(:said_zekr).permit(:zekr_type, :num_of_zekrs, :start_time, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/man_boards_helper.rb
module ManBoardsHelper
end

app/helpers/mohrs_helper.rb
module MohrsHelper
end

app/helpers/namazs_helper.rb
module NamazsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/ruzes_helper.rb
module RuzesHelper
end

app/helpers/said_zekrs_helper.rb
module SaidZekrsHelper
end

app/helpers/yadavars_helper.rb
module YadavarsHelper
end

app/helpers/zekrs_helper.rb
module ZekrsHelper
end

app/views/said_zekrs/_form.html.erb
<%= form_for(@said_zekr) do |f| %>
  <% if @said_zekr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@said_zekr.errors.count, "error") %> prohibited this said_zekr from being saved:</h2>

      <ul>
      <% @said_zekr.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :zekr_type %><br>
    <%= f.text_field :zekr_type %>
  </div>
  <div class="field">
    <%= f.label :num_of_zekrs %><br>
    <%= f.number_field :num_of_zekrs %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.number_field :start_time %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.number_field :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/said_zekrs/edit.html.erb
<h1>Editing Said Zekr</h1>

<%= render 'form' %>

<%= link_to 'Show', @said_zekr %> |
<%= link_to 'Back', said_zekrs_path %>

app/views/said_zekrs/index.html.erb
<!be name anke parvane heirane ust..>

              <div class="row mt">
                  <div class="col-md-12">
                      <div class="content-panel">
                          <table class="table table-striped table-advance table-hover">
                            <h4 ><i class="fa fa-angle-right"></i> > ذکرهای گفته شده </h4>
                            <hr>
                              <thead>
                              <tr>
                                  <th><i class="fa fa-bullhorn"></i> نام</th>
                                  <th class="hidden-phone"><i class="fa fa-question-circle"></i> تعداد</th>
                                  <th class="hidden-phone"><i class="fa fa-question-circle"></i> تاریخ</th>
                                  <th class="hidden-phone"><i class="fa fa-question-circle"></i> ساعت</th>
                                  <!--th class="hidden-phone"><i class="fa fa-question-circle"></i> تاریخ </th--> 
                                  <th></th>
                              </tr>
                              </thead>
                              <tbody>
                                <% @said_zekrs.each do |zekr| %>
                                      <%
                                        @zekr_time = zekr.created_at
                                     %>
                                  <tr>
                                      <td><%= link_to zekr.zekr_type, zekr ,{:style=>'color:#5bc0de;'} %></td>
                                      <td class="hidden-phone"><%= zekr.num_of_zekrs %></td>
                                      <td><span class="label label-info label-mini"><%= @zekr_time.to_date.to_pdate.strftime("%d / %m / %Y ") %></span></td>
                                       <td><span class="label label-info label-mini"><%= @zekr_time.to_time.strftime("%H : %M  ")  %></span></td>
                                      <!--td><span class="label label-info label-mini"><!%= said_zekr.date %></span></td>
                                      <<td class="hidden-phone"> <!%= said_zekr.start_time %></td>
                                      <td class="hidden-phone"> <!%= said_zekr.start_time %></td>
                                      <td><span class="label label-info label-mini">Due</span></td>-->
                                      <td>
                                          
                                         
                                          <%= link_to 'دور ریز', zekr, method: :delete, data: { confirm: 'Are you sure?' } , :class=>"label label-warning label-mini" %>
                                           <%= link_to 'تصحیح', edit_said_zekr_path(zekr) , :class=>"label label-info label-mini" %>
                                           <%= link_to 'نمایش', zekr , :class=>"label label-success label-mini" %>
                                          <!--<button class="btn btn-success btn-xs"><i class="fa fa-check"></i></button>
                                          <button class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button>
                                          <button class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>-->
                                      </td>
                                  </tr>
                             
                            
                           
                                  
                                <% end %>
                              </tbody>
                          </table>
                          <%= link_to 'ذکر گفته شده جدید', new_said_zekr_path  , :class=>"btn btn-round btn-info" %>
                      </div><!-- /content-panel -->
                  </div><!-- /col-md-12 -->
              </div><!-- /row -->

app/views/said_zekrs/new.html.erb
<h1>New Said Zekr</h1>

<%= render 'form' %>

<%= link_to 'Back', said_zekrs_path %>

app/views/said_zekrs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Zekr type:</strong>
  <%= @said_zekr.zekr_type %>
</p>

<p>
  <strong>Num of zekrs:</strong>
  <%= @said_zekr.num_of_zekrs %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @said_zekr.start_time %>
</p>

<p>
  <strong>Date:</strong>
  <%= @said_zekr.date %>
</p>

<%= link_to 'Edit', edit_said_zekr_path(@said_zekr) %> |
<%= link_to 'Back', said_zekrs_path %>

app/views/said_zekrs/show_user_said_zekrs.html.erb
<p id="notice"><%= notice %></p>

<h1>لیست ذکر های گفته شده</h1>

<table class="table">
  <thead>
    <tr>
      <th>تاریخ</th>
      <th> ساعت</th>
      <th> تعداد</th>
      <th>نوع</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @said_zekrs.each do |zekr| %>
    <%
      @zekr_time = zekr.created_at
    %>
      <tr class= <%= @cl %>>
        <td><%= @zekr_time.to_date.to_pdate.strftime("%d / %m / %Y ") %></td>
        <td><%= @zekr_time.to_time.strftime("%H : %M  ") %></td>
        <td><%= zekr.num_of_zekrs %></td>
        <td><%= zekr.zekr_type %></td>
        <td><%= link_to 'Show', zekr %></td>
        <td><%= link_to 'Edit', edit_said_zekr_path(zekr) %></td>
        <td><%= link_to 'Destroy', zekr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Readed namaz', new_readed_namaz_path %>